apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen2-7b-instruct-tp2
spec:
  model:
    uri: hf://Qwen/Qwen2.5-7B-Instruct
    name: Qwen/Qwen2.5-7B-Instruct
  replicas: 1
  router:
    scheduler: {}
    route: {}
    gateway: {}
  template:
    imagePullSecrets:
    - name: redhat-pull-secret
    containers:
      - name: main
        env:
          - name: VLLM_ADDITIONAL_ARGS
            value: "--tensor-parallel-size 2"
        resources:
          limits:
            cpu: '4'
            memory: 32Gi
            nvidia.com/gpu: "2"
          requests:
            cpu: '2'
            memory: 16Gi
            nvidia.com/gpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 5
